Use symbol API to theme icon
jenkinsci/metrics-plugin pull request #158
Opened 2022-05-15 20:50 UTC by NotMyFault

Fixes [JENKINS-68422](https://issues.jenkins.io/browse/JENKINS-68422), by utilizing the symbol API rather then relying on the default color.

Current look:
![](https://i.imgur.com/2P9qtDL.png)

Proposed change:
![](https://i.imgur.com/snJlmz4.png)

cc @alecharp

2022-05-16 07:40 UTC, alecharp requested changes
The code looked ok, but when I run `mvn hpi:run` with an old run I get:

![Screen Shot 2022-05-16 at 09 36 23](https://user-images.githubusercontent.com/985955/168542245-b0fd95e1-2d1a-4326-9e0b-56b672cce7fb.png)

and had the same problem with a new run:

![Screen Shot 2022-05-16 at 09 38 52](https://user-images.githubusercontent.com/985955/168542867-1e85c7a4-f6ba-461d-b010-18513c08879c.png)

2022-05-16 07:40 UTC, alecharp commented on src/main/resources/jenkins/metrics/impl/TimeInQueueAction/summary.jelly
> +<j:jelly xmlns:j="jelly:core" xmlns:t="/lib/hudson" >
```suggestion
<j:jelly xmlns:j="jelly:core" xmlns:t="/lib/hudson">
```

2022-05-16 08:28 UTC, alecharp commented
I debugged the icon resolution and the `symbol-clock` is never in the `IconSet#iconsByCSSSelector`. Only when running with `2.347`

2022-05-16 08:29 UTC, alecharp commented
(sorry, didn't mean to close the PR, clicked on the wrong button)

2022-05-16 10:36 UTC, NotMyFault commented
> Only when running with 2.347, the icon is found.

Good catch, I forgot to bump the jenkins.version. Should be good now 👍🏻

2022-05-16 10:38 UTC, alecharp commented
So, this is a good fix, but only for the latest weekly release. I would prefer not to require that on this plugin for the moment.

2022-05-16 10:47 UTC, NotMyFault commented
If you prefer to keep it on an LTS line, we can use 2.346.1, once released.

2022-05-16 14:00 UTC, alecharp commented
I would definitively prefer to wait for the LTS to be released.

2022-05-16 14:15 UTC, NotMyFault commented
> I would definitively prefer to wait for the LTS to be released.

I've exchanged the jenkins.version with the weekly the upcoming LTS version is based on. Can increase it to .1 once released.

2022-06-22 16:32 UTC, NotMyFault commented
I didn't forget you @alecharp :P

The plugin has been realigned with today's LTS release of 2.346.1

2022-06-23 14:57 UTC, alecharp approved these changes
Tested locally and couldn't find any problem.

2022-07-21 15:08 UTC, NotMyFault commented
@alecharp anything left that blocks a merge and possible release?

2022-07-21 15:10 UTC, alecharp commented
@NotMyFault nothing, except me. Fixing this now.

2022-07-21 15:10 UTC, merged

2022-07-22 17:57 UTC, jetersen commented
This release is broken for support core, which refuses to load 4.1.6-383.v9d1dd57200e0 because it requires metrics-4.1.6.2 which is higher

https://github.com/jenkinsci/metrics-plugin/releases/tag/4.1.6-383.v9d1dd57200e0 is lower than https://github.com/jenkinsci/metrics-plugin/releases/tag/metrics-4.1.6.2